import Head from 'next/head';
import { Layout } from '../components/layout/layout';
import { Profile } from '../components/profile/profile';
import { RepositorieContent } from '../components/repositorie-content/repositorie-content';

export default function Home() {
  return (
    <>
      <Head>
        <title>Your Repositories | Github</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Layout>
        <Profile />
        <RepositorieContent />
      </Layout>
    </>
  );
}
